# 0389 - Find the Difference

'''
    Question:
        You are given two strings s and t.
        String t is generated by random shuffling string s and then add one more letter at a random position.

        Return the letter that was added to t.
'''

from collections import Counter

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        # Convert the chr to ASCII value, make the summation of the string t.
        # Once the summation finished, we can apply the subtraction of s.
        ans = 0
        for ascii_chr in t: ans += ord(ascii_chr)
        for ascii_chr in s: ans -= ord(ascii_chr) # ord returns ASCII value
        return chr(ans) # chr() converts ASCII into character
    
if __name__ == '__main__':
    s = "abcd"
    t = "abcde"
    sol = Solution()
    print(sol.findTheDifference(s, t))